### ISSUE TITLE
Scaling a non blu/green app fails

### ISSUE THREAD

**Issue by ocraviotto** [comptelfwd/quarrier#12]
Scaling down a non blue-green deployment failed with:
```
[9461] Failed to execute script cli
Traceback (most recent call last):
  File "quarrier/cli.py", line 1232, in <module>
  File "quarrier/cli.py", line 135, in main
  File "site-packages/dcos/cmds.py", line 43, in execute
  File "quarrier/cli.py", line 1183, in scale
KeyError: 'marathon_lb
``` 
quarrier version: `0.2.0`

**Comment by ocraviotto** [comment]
Fixed by #23
